# Generated by Django 4.2.5 on 2023-09-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
