# Generated by Django 4.2.5 on 2023-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0002_remove_user_id_alter_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('example_input', models.TextField()),
                ('example_output', models.TextField()),
            ],
        ),
    ]
