# Generated by Django 4.2.5 on 2023-09-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0003_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DOB',
        ),
    ]
