# Generated by Django 4.2.5 on 2023-09-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0004_remove_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
