# Generated by Django 4.2.5 on 2023-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='example_explain',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='example_input',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='example_output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(default=''),
        ),
    ]
