# Generated by Django 4.2.5 on 2023-10-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0008_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserName',
            new_name='username',
        ),
    ]
